### ISSUE TITLE
feat(app-shell): it would be nice to work with app-shell and ng new --mobile

### ISSUE THREAD

**Issue by Splaktar** [platosha/angular-polymer#26]
There are issues when using this with a [Mobile Toolkit](https://mobile.angular.io/) project, specifically with [app-shell](https://github.com/angular/mobile-toolkit/tree/master/app-shell) by @mgechev. 
You can find the docs to create one of these projects with the angular-cli [here](https://github.com/angular/mobile-toolkit/blob/master/guides/cli-setup.md).

Everything works fine up until you try to actually use of the Polymer elements via something like:

``` javascript
PolymerElement('paper-toolbar')
```

Then you get errors due to the use of `window`:

``` javascript
var Polymer = window.Polymer;
ReferenceError: window is not defined
```

``` bash
angular-cli: 1.0.0-beta.6
node: 4.4.3
os: darwin x64
```

```
"dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@vaadin/angular2-polymer": "1.0.0-beta1",
    "angular2-broccoli-prerender": "0.11.5",
    "angular2-express-engine": "0.13.0",
    "angular2-universal": "0.100.5",
    "angular2-universal-polyfills": "0.4.1",
    "angularfire2": "2.0.0-beta.1",
    "body-parser": "1.15.1",
    "es6-shim": "0.35.1",
    "firebase": "3.0.4",
    "preboot": "2.1.2",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "@angular/service-worker": "0.2.0",
    "@angular/app-shell": "0.0.0",
    "angular-cli": "1.0.0-beta.6",
    "codelyzer": "0.0.20",
    "ember-cli-inject-live-reload": "1.4.0",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "1.0.1",
    "karma-jasmine": "1.0.2",
    "protractor": "3.3.0",
    "ts-node": "0.7.3",
    "tslint": "3.11.0",
    "typescript": "1.8.10",
    "typings": "0.8.1"
  }
```

This exception occurs:

``` bash
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: /bin/sh -c node /Users/splaktar/Git/tf/webapp/node_modules/angular2-broccoli-prerender/dist/child_proc.js  --sourceHtml=/Users/splaktar/Git/tf/webapp/tmp/app_shell_plugin-input_base_path-SJdQBGZZ.tmp/0/index.html --optionsPath=/Users/splaktar/Git/tf/webapp/tmp/app_shell_plugin-input_base_path-SJdQBGZZ.tmp/0/main-app-shell --outputIndexPath=/Users/splaktar/Git/tf/webapp/tmp/app_shell_plugin-output_path-pj5EpfjV.tmp/index.html
/Users/splaktar/Git/tf/webapp/node_modules/@vaadin/angular2-polymer/src/polymer-element.js:11
var Polymer = window.Polymer;
              ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/splaktar/Git/tf/webapp/node_modules/@vaadin/angular2-polymer/src/polymer-element.js:11:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/splaktar/Git/tf/webapp/node_modules/@vaadin/angular2-polymer/index.js:2:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)

The broccoli plugin was instantiated at: 
    at AppShellPlugin.Plugin (/Users/splaktar/Git/tf/webapp/node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (/Users/splaktar/Git/tf/webapp/node_modules/broccoli-caching-writer/index.js:21:10)
    at new AppShellPlugin (/Users/splaktar/Git/tf/webapp/node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/lib/broccoli/angular2-app.js:153:48)
    at new Angular2App (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/splaktar/Git/tf/webapp/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/splaktar/Git/tf/webapp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
```

Thanks for making this available! I'm disabling app-shell in my project for now by making this change to `angular-cli.json`:

``` json
    "mobile": false
```

**Comment by Splaktar** [comment]
Looks like it might be possible to use something similar to angular-universal's `DomAdapter` instead of `window`. From comment here: https://github.com/angular/universal/issues/445#issuecomment-228610263

**Comment by MarkPieszak** [comment]
That would be ideal! I'm currently on vacation but will see what I can do to get this working with Universal sometime next week. Would love to have polymer + angular2 integration working ! :)

**Comment by MarkPieszak** [comment]
So bad news unfortunately :(
Talked to a few people, unfortunately it seems Polymer is completely based on the browser and DOM you would need to basically create a new (different Polymer) for it to work server rendered. Don't think you'll be able to incorporate Polymer with Universal. It just wasn't created the way angular2 was (with those things in mind) 
@splaktar

**Comment by platosha** [comment]
Depending on the way Polymer elements are used in Angular 2 apps, it might not be a bad solution to have Polymer disabled on server. If on server we just treat Polymer elements as regular HTML, render the app state within this high level of abstraction, then send it to the Polymer-enabled browser, it should work.

The only rule for the app developers to respect is that we can not put the application logic inside Polymer elements. So, basically, this way we should consider Polymer elements as presentational-only stateless components. It does make sense in such a use case, we have Angular 2 to build the app state and logic.

With that in mind, in the angular2-polymer package we have to try to gracefully stop doing any work if the environment is not browser, without throwing errors. This should make the app running on server and rendering Polymer elements as a regular HTML markup.

**Comment by MarkPieszak** [comment]
Well said, I agree I think that's just about the most we could do for now. Maybe within universal we could DI out some of those window Polymer methods etc to get ignored/do nothing like you're saying, at least it'd still work on the server side (wouldn't break at least!)

**Comment by Splaktar** [comment]
That sounds like enough of a solution for now. I really just need to be able to render the app-shell with Universal, not the whole functional app. 

The problem I had before was that even with `*shellNoRender` around all of the Polymer elements (meaning don't render in app-shell), initializing Polymer is still calling `window.Polymer;`.

I'll try to mess with this again sometime soon, but any changes that could be made to keep from throwing exceptions in `polymer-element.js` when `window` doesn't exist would be appreciated.
