### ISSUE TITLE
UX: Improve "Cannot read property 'forEach' of undefined" error msg

### ISSUE THREAD

**Issue by Splaktar** [platosha/angular-polymer#27]
Currently the output of `Cannot read property 'forEach' of undefined` is really hard for beginners to diagnose. This can be caused by a number of things and it would be nice to either have the docs cover it or to improve the error message.

Causes
- When passing in invalid components to PolymerElement like `PolymerElement('thanks-vaadin')`
- Not importing the component via something like `<link rel="import" href="bower_components/iron-icons/av-icons.html">`
- Probably some others...

Full stack trace:

``` javascript
zone.js:461 Unhandled Promise rejection: TypeError: Cannot read property 'forEach' of undefined
        at Object.PolymerElement (http://localhost:4200/vendor/@vaadin/angular2-polymer/src/polymer-element.js:71:20)
        at eval (http://localhost:4200/app/+landing/landing.component.js:41:36)
        at Object.eval (http://localhost:4200/app/+landing/landing.component.js:48:2)
        at eval (http://localhost:4200/app/+landing/landing.component.js:51:4)
        at eval (http://localhost:4200/app/+landing/landing.component.js:52:3)
    Evaluating http://localhost:4200/app/+landing/landing.component.js
    Evaluating http://localhost:4200/app/+landing/index.js
    Evaluating http://localhost:4200/app/app.component.js
    Evaluating http://localhost:4200/app/index.js
    Evaluating http://localhost:4200/main.js
    Error loading http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: TypeError: Cannot read property 'forEach' of undefined(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426

zone.js:463 Error: Uncaught (in promise): Error: TypeError: Cannot read property 'forEach' of undefined(…)
    consoleError        @   zone.js:463
    _loop_1             @   zone.js:490
    drainMicroTaskQueue @   zone.js:494
    ZoneTask.invoke     @   zone.js:426
```

**Comment by manolo** [comment]
Yes, the component should be registered before using it.
Any error like bad element name or import not run yet would produce this output.
We still have to work to give more accurate errors to the user.
