### ISSUE TITLE
Getting values from Polymer Elements in Angular 2 components

### ISSUE THREAD

**Issue by nicholaschantcs** [platosha/angular-polymer#50]
I have been trying to implement polymer elements into an angular 2 application and this module works just fine for predefined polymer elements from their official site. However, I am trying to implement custom elements such as [DigElements](https://github.com/DigElements), an example usecase will be using [elastic-client](https://github.com/DigElements/elastic-client). I am able to pass in data into

in a non-angular 2 application, the returned value will be passed to client which then assigned to esclient in the dom element. However, I don't think this will work in an angular 2 application as angular treats `{{esclient}}` as an Input rather than Output.

``` html

<elastic-client
config='{"host": "http://localhost:9200"}'
client="{{esclient}}"></elastic-client>

```

in an angular 2 application, we can inject data into polymer elements using `[ ]` but is there a way of access the properties of the data and pass that to the angular 2 component? 

``` html
<elastic-client
[config]='{"host": "http://localhost:9200"}'></elastic-client>
```

I have tried using native html element API to retrieve the properties of the polymer element but I think the method I was using was quite a messy one due to the behaviour of the polymer element which is works asynchronously.

I wonder if there is a way to of getting the callback data from a polymer element using this PolymerElement component?

Please advice.

Thanks
Nicholas

**Comment by Saulis** [comment]
Hi!

The simplest way should be just using normal two-way binding.
Using the example from `elastic-client` readme:

``` html
<elastic-client
config='{"host": "http://localhost:9200"}'
client="{{esclient}}"></elastic-client>

<elastic-search 
client="[[esclient]]"
index="myindex"
index-type="[[indexType]]"
query-results="{{results}}"></elastic-search>
```

Equals to this in Angular 2:

``` html
<elastic-client
[config]='{"host": "http://localhost:9200"}'
[(client)]="esclient"></elastic-client>

<elastic-search 
[client]="esclient"
index="myindex"
[index-type]="indexType"
[(query-results)]="results"></elastic-search>
```

And you should have the results in property `results` that you've defined in your Angular2 component. Alternatively, you can register a handler function using syntax: `(query-results-change)='handleResults($event)'`

**Comment by nicholaschantcs** [comment]
Hi Saulis, 

Thanks for the heads up on using two-way binding, I have managed to get the values of clusterStatus and client from < elastic-client > element by using two-way binding.

``` html
<elastic-client 
    [config]="config"
    [(client)]="esClient" 
    [(clusterStatus])="clusterStatus">
</elastic-client>
```

I believed the variables for two way binding is from the properties of the Polymer elements as below right?

``` javascript
Polymer({
    is: 'elastic-client',
    properties: {
      config: {
        type: Object,
        observer: '_createEsClient'
      },
      clusterStatus: {
        type: String,
        value: 'down',
        notify: true
      },
      client: {
        type: Object,
        notify: true
      }
    },
    _createEsClient: function(config) {
      this.client = new elasticsearch.Client(config);
      var self = this;

      this.client.ping({
        requestTimeout: 30000,
        hello: 'elasticsearch'
      })
      .then(function () {
        self.clusterStatus = 'up';
      })
      .catch(function(error) {
        console.error('elasticsearch cluster is down!', error);
      });
    }
  });
```

so If I tried to use the same approach on < elastic-search > element. I think there was some errors on the readme on < elastic-search > element as [elastic-search](https://github.com/DigElements/elastic-search/blob/master/elastic-search.html) rather than `query-results`, it should be `results`. 

``` javascript
  Polymer({
    is: 'elastic-search',
    properties: {
      client: {
        type: Object
      },
      index: {
        type: String
      },
      elasticType: {
        type: Array,
        value: []
      },
      query: {
        type: Object,
        observer: '_resetPage'
      },
      results: {
        type: Object,
        notify: true,
        readOnly: true
      },
...

```

After trying the below example, I am getting some errors regarding no setter for element probably because of the two-way binding that doesn't allow me 
 to inject data into [results]. I tried both two-way binding and `(results-change)` but the change callback isn't being called in angular 2 components. Any idea on how to proceed on this?

Regards
Nicholas

``` html
<elastic-search [hidden]="!clusterStatus"
      [client]="esclient"
      [index]="index"
      [body]='{"query": {"bool": {"must":{}}}}'
      [(results)]="esResults"
      (results-change)="handleResults($event)">
</elastic-search>
```

``` javascript
TypeError: Cannot set property results of #<elastic-search> which has only a getter
    at PolymerShadyDomAdapter.BrowserDomAdapter.setProperty (http://localhost:3333/node_modules/@angular/platform-browser/platform-browser.umd.js:954:89)
    at DomRenderer.setElementProperty (http://localhost:3333/node_modules/@angular/platform-browser/platform-browser.umd.js:1972:22)
    at DebugDomRenderer.setElementProperty (http://localhost:3333/node_modules/@angular/core/core.umd.js:10232:28)
    at DebugAppView._View_DashboardComponent0.detectChangesInternal (DashboardComponent.template.js:363:19)
    at DebugAppView.AppView.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:9996:18)
    at DebugAppView.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:10084:48)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:10016:38)
    at DebugAppView._View_DashboardComponent_Host0.detectChangesInternal (DashboardComponent_Host.template.js:36:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:9996:18)
    at DebugAppView.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:10084:48)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:10011:41)
    at DebugAppView._View_AppComponent0.detectChangesInternal (AppComponent.template.js:399:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:9996:18)
    at DebugAppView.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:10084:48)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:10016:38)
    at DebugAppView._View_AppComponent_Host0.detectChangesInternal (AppComponent_Host.template.js:59:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:9996:18)
    at DebugAppView.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:10084:48)
    at ViewRef_.detectChanges (http://localhost:3333/node_modules/@angular/core/core.umd.js:9397:69)
    at eval (http://localhost:3333/node_modules/@angular/core/core.umd.js:9047:88)
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:3333/node_modules/@angular/core/core.umd.js:9047:42)
    at eval (http://localhost:3333/node_modules/@angular/core/core.umd.js:8953:121)
    at ZoneDelegate.invoke (http://localhost:3333/node_modules/zone.js/dist/zone.js:323:29)
    at Object.onInvoke (http://localhost:3333/node_modules/@angular/core/core.umd.js:6075:45)
    at ZoneDelegate.invoke (http://localhost:3333/node_modules/zone.js/dist/zone.js:322:35)
    at Zone.run (http://localhost:3333/node_modules/zone.js/dist/zone.js:216:44)
    at NgZoneImpl.runInner (http://localhost:3333/node_modules/@angular/core/core.umd.js:6106:75)
    at NgZone.run (http://localhost:3333/node_modules/@angular/core/core.umd.js:6330:70)
    at Object.eval (http://localhost:3333/node_modules/@angular/core/core.umd.js:8953:97)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3333/node_modules/@angular/core/core.umd.js:6007:56)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3333/node_modules/rxjs/Subscriber.js:225:16)
    at SafeSubscriber.next (http://localhost:3333/node_modules/rxjs/Subscriber.js:174:22)
    at Subscriber._next (http://localhost:3333/node_modules/rxjs/Subscriber.js:124:26)
    at Subscriber.next (http://localhost:3333/node_modules/rxjs/Subscriber.js:88:18)
    at EventEmitter.Subject._finalNext (http://localhost:3333/node_modules/rxjs/Subject.js:128:30)
    at EventEmitter.Subject._next (http://localhost:3333/node_modules/rxjs/Subject.js:120:18)
    at EventEmitter.Subject.next (http://localhost:3333/node_modules/rxjs/Subject.js:77:14)
    at EventEmitter.emit (http://localhost:3333/node_modules/@angular/core/core.umd.js:5996:80)
    at NgZone._checkStable (http://localhost:3333/node_modules/@angular/core/core.umd.js:6248:48)
    at NgZoneImpl.setMicrotask (http://localhost:3333/node_modules/@angular/core/core.umd.js:6224:27)
    at Object.onHasTask (http://localhost:3333/node_modules/@angular/core/core.umd.js:6087:39)
    at ZoneDelegate.hasTask (http://localhost:3333/node_modules/zone.js/dist/zone.js:382:56)
    at ZoneDelegate._updateTaskCount (http://localhost:3333/node_modules/zone.js/dist/zone.js:399:27)
    at ZoneDelegate.invokeTask (http://localhost:3333/node_modules/zone.js/dist/zone.js:360:27)
    at Zone.runTask (http://localhost:3333/node_modules/zone.js/dist/zone.js:256:48)
    at drainMicroTaskQueue (http://localhost:3333/node_modules/zone.js/dist/zone.js:474:36)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3333/node_modules/zone.js/dist/zone.js:426:22)
```

**Comment by Saulis** [comment]
@nicholaschantcs yeah you need to remove the two-way binding (`[(results)]="esResults"`) since `results` has `readOnly: true`. And also, my bad – the correct syntax for the callback handler would be `(resultsChange)="handleResults($event)"` without the dash.

**Comment by nicholaschantcs** [comment]
Thanks for the help @Saulis , it's the callbacks are working as they should be now.
